/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

char *__fastcall concatenate(const char *a, const char *b, char *a3); // idb
int __cdecl main(int argc, const char **argv, const char **envp);
// __int64 __fastcall memcpy(_QWORD, _QWORD, _QWORD, _QWORD); weak
// void *__cdecl malloc(size_t);
// int printf(const char *, ...);
// int scanf(const char *, ...);
// unsigned int __cdecl sleep(unsigned int);
// size_t __cdecl strlen(const char *);
// int __cdecl system(const char *);

//-------------------------------------------------------------------------
// Data declarations

// extern _UNKNOWN __stack_chk_guard; weak


//----- (0000000100001500) ----------------------------------------------------
char *__fastcall concatenate(const char *a, const char *b, char *a3)
{
  char *res; // [rsp+28h] [rbp-38h]
  size_t alen; // [rsp+30h] [rbp-30h]
  size_t blen; // [rsp+38h] [rbp-28h]
  size_t clen; // [rsp+40h] [rbp-20h]
  const char *c; // [rsp+48h] [rbp-18h]

  c = a3;
  clen = strlen(a);
  blen = strlen(b);
  alen = strlen(c);
  res = (char *)malloc(alen + blen + clen + 1);
  if ( res )
  {
    memcpy(res, a, clen, -1LL);
    memcpy(&res[clen], b, blen, -1LL);
    memcpy(&res[clen + blen], c, alen + 1, -1LL);
  }
  return res;
}
// 1000019C2: using guessed type __int64 __fastcall memcpy(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000001000015F0) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  char *invapfs1; // STC8_8
  int result; // eax
  char opt; // [rsp+E4h] [rbp-1Ch]
  char invapfs2; // [rsp+E9h] [rbp-17h]
  __int64 v7; // [rsp+F8h] [rbp-8h]

  system("clear");
  printf("-----------------------\n", argv);
  printf("DuffyAPP_IT - iBootX Beta 2\nPlease Check PDF Instructions Before Executing\n");
  printf("-----------------------\n");
  printf("Ensure you have executed this from the terminal, and not by double clicking the binary..\n\n");
  printf("The current working directory is:\n");
  system("pwd");
  printf("Enter a random number between 1 and 9, and press enter to confirm rootfs.dmg is in the current folder: \n");
  scanf("%d", &opt);
  printf("\nRunning..\n");
  sleep(3u);
  system("asr -source rootfsin.dmg -target rootfsout.dmg --embed -erase -noprompt --chunkchecksum --puppetstrings");
  printf("Starting VirtualInstall...");
  sleep(4u);
  printf("Creating Virtual APFS Disk\n");
  system("hdiutil create -size 10GB -fs APFS -volname iOS iOS.dmg  >/dev/null 2>&1");
  printf("\nCreated\n");
  sleep(1u);
  printf("Attaching VDisk\n");
  system("hdiutil attach iOS.dmg");
  printf(
    "Enter Disk identifier of */Volumes/iOS* (probably the last entry)\n"
    "in the form /dev/diskXsX from the output above: ");
  scanf("%s", &invapfs2);
  invapfs1 = concatenate(
               "sudo /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs_invert -d ",
               &invapfs2,
               " -s 1 -n rootfsout.dmg");
  printf("\nWaiting For Connection To Disk...\n", &invapfs2);
  sleep(8u);
  printf("Connected\n");
  sleep(1u);
  printf("Moving iOS RootFS\n");
  system("cp rootfsout.dmg /Volumes/iOS/rootfsout.dmg  >/dev/null 2>&1");
  printf("\ncmd complete\n");
  system("umount /Volumes/iOS");
  printf("Unmounted VDisk\n");
  sleep(1u);
  printf("Preparing To Invert iOS APFS Disk\n");
  printf("\n");
  system(invapfs1);
  printf("\nImage Success.. Compressing\n");
  sleep(3u);
  printf("Mount iOS VDisk..\n");
  system("hdiutil attach iOS.dmg  >/dev/null 2>&1");
  printf("\nConnecting..\n");
  sleep(7u);
  printf("\nConnected.\n");
  sleep(2u);
  system("tar -zcf  iOSout.tar.gz /Volumes/iOS  >/dev/null 2>&1");
  printf("\niOS Succesfully Compressed.\nUnmounting iOS VDisk\n");
  system("sudo umount /Volumes/iOS");
  printf("\nDisk was succesfully unmounted..\n");
  result = printf("\nProcess Complete\n");
  if ( __stack_chk_guard == v7 )
    result = 0;
  return result;
}

// ALL OK, 2 function(s) have been successfully decompiled
